#!/usr/bin/env bash
# Docker Kernel Build Script

# Start Compile
BUILD_START=$(date +"%s")

# For overclock version
if
   [[ "$OC" == "-overclock" ]]; then
     wget https://raw.githubusercontent.com/XSans02/CI_Script/main/tulip-patch/oc.patch
     
     wget https://raw.githubusercontent.com/XSans02/CI_Script/main/tulip-patch/em.patch
     
     git apply oc.patch
     
     git apply em.patch
fi

make 0=out "$DEVICE"_defconfig

make -j"$(nproc --all)" 0=out \
                   ARCH="$ARCH" \
                   SUBARCH="$SUBARCH" \
                   CC=clang \
                   CROSS_COMPILE=aarch64-linux-gnu- \
                   CROSS_COMPILE_ARM32=arm-linux-gnueabi-

BUILD_END=$(date +"%s")
DIFF=$(( BUILD_END - BUILD_START ))

# If build error
if ! [ -a "$KERNEL_IMG" ]; then
  sendInfo "<b>Failed building kernel for <code>$LOCALVERSION</code> Please fix it...!</b>"
  exit 1
fi

# Making zip
cp -r "$KERNEL_IMG" "$AK3_DIR"/
cd "$AK3_DIR" || exit

if [[ "$*" =~ "beta" ]]; then
  zip -r9 "$LOCALVERSION"_"$ZIP_DATE".zip ./*
else
  zip -r9 "$LOCALVERSION"_"$ZIP_DATE".zip ./*
fi

cd "$KERNEL_DIR" || exit