#!/usr/bin/env bash
# Copyright ©2021 XSans02
# Docker Kernel Build Script

# Cloning some resource
if [[ "$*" =~ "beta" ]]; then
  TYPE=Beta
  git clone --depth=1 https://github.com/XSans02/kernel_xiaomi_sdm660 -b 12-bpf-test kernel
  DEFCONFIG=tulip_defconfig
  cd kernel || exit
elif [[ "$*" =~ "stable" ]]; then
  TYPE=Stable
  git clone --depth=1 https://github.com/XSans02/kernel_xiaomi_sdm660 -b 12-bpf kernel
  DEFCONFIG=tulip_defconfig
  cd kernel || exit
fi

# If newcam
if [[ "$*" =~ "newcam" ]]; then
   sed -i 's/CONFIG_MACH_XIAOMI_NEW_CAMERA=n/CONFIG_MACH_XIAOMI_NEW_CAMERA=y/g' kernel/arch/arm64/configs/$DEFCONFIG
   CAM=NewCam
else
   CAM=OldCam
fi

if [[ "$*" =~ "clang" ]]; then
  # git clone --depth=1 https://github.com/sohamxda7/llvm-stable -b aosp-13.0.3 clang
  git clone --depth=1 https://github.com/kdrag0n/proton-clang clang
  # git clone --depth=1 https://github.com/XSans02/clang-14 clang
elif [[ "$*" =~ "gcc" ]]; then
  # git clone --depth=1 https://github.com/mvaisakh/gcc-arm64 -b gcc-master arm64
  # git clone --depth=1 https://github.com/mvaisakh/gcc-arm -b gcc-master arm32
  # git clone --depth=1 https://github.com/sohamxda7/llvm-stable -b gcc64 arm64
  # git clone --depth=1 https://github.com/sohamxda7/llvm-stable -b gcc32 arm32
  git clone --depth=1 https://github.com/fiqri19102002/aarch64-gcc.git -b gnu-gcc-10-tarballs arm64
  git clone --depth=1 https://github.com/fiqri19102002/arm-gcc.git -b gnu-gcc-10-tarballs arm32
fi

git clone --depth=1 https://github.com/XSans02/telegram.sh.git Telegram
git clone --depth=1 https://github.com/XSans02/AnyKernel3.git -b master ak3

# Version setup
if [[ "$TYPE" == "Beta" ]]; then
   LOCALVERSION="$CAM"-"$TYPE"
else
   LOCALVERSION="$CAM"
fi

# Setup Environtment
KERNEL_DIR=$PWD
KERNEL_IMG=$KERNEL_DIR/out/arch/arm64/boot/Image.gz-dtb
DEVICE=tulip
KBUILD_BUILD_USER="XSansツ"
KBUILD_BUILD_HOST="CircleCI-Server"
AK3_DIR=$KERNEL_DIR/ak3/
export TZ="Asia/Jakarta"
ZIP_DATE=$(TZ=Asia/Jakarta date +'%d%m%Y')
ZIP_DATE2=$(date +"%H%M")
SOURCE="$(git rev-parse --abbrev-ref HEAD)"
COMMIT=$(git log --pretty=format:'%s' -1)

if [[ "$*" =~ "clang" ]]; then
  # Kernel & Clang Setup
  TC=clang
  CLANG_DIR="$KERNEL_DIR/clang"
  export PATH="$KERNEL_DIR/clang/bin:$PATH"
  KBUILD_COMPILER_STRING="$("$CLANG_DIR"/bin/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')"
  export KBUILD_COMPILER_STRING
elif [[ "$*" =~ "gcc" ]]; then
  # Kernel & GCC setup
  TC=gcc
  GCC_DIR="$KERNEL_DIR"/arm64
  export PATH="$KERNEL_DIR/arm64/bin:$KERNEL_DIR/arm32/bin:$PATH"
  KBUILD_COMPILER_STRING="$("$GCC_DIR"/bin/aarch64-linux-gnu-gcc --version | head -n 1)"
  export KBUILD_COMPILER_STRING
fi

# Generate a full DEFCONFIG prior building. 1 is YES | 0 is NO(default)
DEF_REG=0

export ZIP_DATE
export ZIP_DATE2
export SOURCE
export ARCH=arm64
export SUBARCH=arm64
export KBUILD_BUILD_USER
export KBUILD_BUILD_HOST
export LOCALVERSION

# Telegram
TELEGRAM=Telegram/telegram
sendInfo() {
  "${TELEGRAM}" -c "${CHANNEL_ID}" -H -D \
      "$(
          for POST in "${@}"; do
              echo "${POST}"
          done
      )"
}

sendKernel() {
  "${TELEGRAM}" -f "$(echo "$AK3_DIR"/*.zip)" \
  -c "${CHANNEL_ID}" -H \
      "# <code>$DEVICE</code> # <code>md5: $(md5sum "$AK3_DIR"/*.zip | cut -d' ' -f1)</code> # <code>Build Took : $(("$DIFF" / 60)) Minute, $(("$DIFF" % 60)) Second</code>"
}

sendInfo  "<b>*******************************************</b>" \
          "<b>Start Building :</b> <code>NTR Kernel</code>" \
          "<b>Device : </b><code>$DEVICE</code>" \
          "<b>Status : </b><code>$TYPE</code>" \
          "<b>CamVersion: </b><code>$CAM</code>" \
          "<b>Source Branch :</b> <code>$SOURCE</code>" \
          "<b>*******************************************</b>"

# Start Count
BUILD_START=$(date +"%s")

if [[ "$TC" == "clang" ]]; then
    make O=out ARCH=arm64 "$DEFCONFIG"
    if [ $DEF_REG = 1 ]; then
	cp .config arch/arm64/configs/$DEFCONFIG
	git add arch/arm64/configs/$DEFCONFIG
	git commit -m "$DEFCONFIG: Regenerate
					This is an auto-generated commit"
    fi
    make -j$(nproc --all) O=out \
                    ARCH=arm64 \
                    SUBARCH=arm64 \
                    LD_LIBRARY_PATH="${CLANG_DIR}/lib:${LD_LIBRARY_PATH}" \
                    CC=clang \
                    AR=llvm-ar \
                    NM=llvm-nm \
                    OBJCOPY=llvm-objcopy \
                    OBJDUMP=llvm-objdump \
                    STRIP=llvm-strip \
                    LD=ld.lld \
                    CLANG_TRIPLE=aarch64-linux-gnu- \
                    CROSS_COMPILE=aarch64-linux-gnu- \
                    CROSS_COMPILE_ARM32=arm-linux-gnueabi-
elif [[ "$TC" == "gcc" ]]; then
    make O=out ARCH=arm64 "$DEFCONFIG"
    make -j$(nproc --all) O=out \
                    ARCH=arm64 \
                    SUBARCH=arm64 \
                    CROSS_COMPILE=aarch64-linux-gnu- \
                    CROSS_COMPILE_ARM32=arm-linux-gnueabi-
fi

# If build error
if ! [ -a "$KERNEL_IMG" ]; then
  sendInfo "<b>Failed building kernel for <code>$DEVICE</code> Please fix it...!</b>"
  exit 1
fi

# End Count and Calculate Total Build Time
BUILD_END=$(date +"%s")
DIFF=$(( BUILD_END - BUILD_START ))

LINUX_VERSION=$(cat < out/.config | grep Linux/arm64 | cut -d " " -f3)

# Make zip
cp -r "$KERNEL_IMG" "$AK3_DIR"/

cd "$AK3_DIR" || exit

# Packing zip
ZIP_NAME=NTR-Yoshizawa

zip -r9 ["$ZIP_DATE2"]["$TYPE"]["$CAM"]"$ZIP_NAME"-"$ZIP_DATE".zip ./*

cd "$KERNEL_DIR" || exit

sendKernel
sendInfo  "<b>*******************************************</b>" \
          "<b>Success Building :</b> <code>NTR Kernel</code>" \
          "<b>Linux Version :</b> <code>$LINUX_VERSION</code>" \
          "<b>Build Date :</b> <code>$(date +"%A, %d %b %Y, %H:%M:%S")</code>" \
          "<b>Compiler :</b> <code>$KBUILD_COMPILER_STRING</code>" \
          "<b>Last Commit :</b> <code>$COMMIT</code>" \
          "<b>*******************************************</b>"
