#!/usr/bin/env bash
# Kernel Build Script with proton clang

# Setup kernel saus
if 
   [[ "$*" =~ "beta" ]]; then
     git clone --depth=1 https://github.com/XSans02/kernel_xiaomi_sdm660.git -b arrow-12.0 kernel
     cd kernel | exit
     TYPE=-beta
elif
   [[ "$*" =~ "stable" ]]; then
     git clone --depth=1 https://github.com/XSans02/kernel_sdm660.git -b eas kernel
     TYPE=-stable
     cd kernel | exit
fi

# Setup oldcam or newcam
if
   [[ "$*" =~ "oldcam" ]]; then
     CAM=-oldcam
elif
   [[ "$*" =~ "newcam" ]]; then
     CAM=-newcam
     CONFIG=-newcam
fi

# Setup for Overclock version
if
   [[ "$*" =~ "oc" ]]; then
     OC=-overclock
fi

git clone --depth=1 https://github.com/kdrag0n/proton-clang.git proton

git clone --depth=1 https://github.com/XSans02/telegram.sh.git Telegram

git clone --depth=1 https://github.com/XSans02/AnyKernel3.git

# Telegram bot setup
TELEGRAM=Telegram/telegram
send_msg() {
  "${TELEGRAM}" -c "${CHANNEL_ID}" -H -D \
      "$(
          for POST in "${@}"; do
              echo "${POST}"
          done
      )"
}

send_kernel() {
  "${TELEGRAM}" -f "$(echo "$AK3_DIR"/*.zip)" \
  -c "${CHANNEL_ID}" -H \
      "# <code>$DEVICE</code>%0A<code>md5: $(md5sum "$AK3_DIR"/*.zip | cut -d' ' -f1)</code> # <code>Build Took : $(("$DIFF" / 60)) Minute, $(("$DIFF" % 60)) Second</code>"
}

# Environment setup
KERNEL_DIR="$pwd"
KERNEL_IMG="$KERNEL_DIR"/out/arch/arm64/boot/Image.gz-dtb
KERNEL_NAME=Waifu:Raiden-EAS
LINUX=v"$(make kernelversion)"
TC_DIR="$KERNEL_DIR"/proton
PATH="$TC_DIR"/bin:$PATH"
KBUILD_COMPILER_STRING="$("$TC_DIR"/bin/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')"
DEVICE=tulip
LOCALVERSION="$KERNEL_NAME""$TYPE""$CAM""$OC"
AK3_DIR="$KERNEL_DIR"/AnyKernel3
ARCH=arm64
SUBARCH=arm64
KBUILD_BUILD_USER="XSans02"
KBUILD_BUILD_HOST="CircleCI-Server"
SOURCE="$(git rev-parse --abbrev-ref HEAD)"
COMMIT="$(git log --pretty=format:'%s' -1)"

# Export
export LINUX
export PATH
export KBUILD_COMPILER_STRING
export LOCALVERSION
export ARCH
export SUBARCH
export KBUILD_BUILD_USER
export KBUILD_BUILD_HOST
export SOURCE
export COMMIT
export TZ="Asia/Jakarta"
export ZIP_DATE=$(TZ=Asia/Jakarta date +'%d%m%Y')

send_msg " " \
            "<b>Start Build: </b><code>$LOCALVERSION</code>" \
            "<b>Linux version: </b><code>$LINUX</code>" \
            "<b>Compiler: </b><code>$KBUILD_COMPILER_STRING</code>" \
            "<b>Branch: </b><code>$SOURCE</code>" \
            "<b>Last Commit: </b><code>$COMMIT</code>"