#!/usr/bin/env bash
# Copyright (C) 2021 Oktapra Amtono <oktapra.amtono@gmail.com>
# Kernel Build Script

# Kernel Directory
KERNEL_DIR=$PWD

RELEASE_VERSION="-Rev1.1"

KERNEL_NAME="Waifu-EiChan-EAS"

# Device Name
if [[ "$*" =~ "whyred" ]]; then
  DEVICE="whyred"
  export LOCALVERSION="$RELEASE_VERSION"
elif [[ "$*" =~ "tulip" ]]; then
  DEVICE="tulip"
  export LOCALVERSION="$RELEASE_VERSION"
elif [[ "$*" =~ "lavender" ]]; then
  DEVICE="lavender"
  export LOCALVERSION="$RELEASE_VERSION"
elif [[ "$*" =~ "a26x" ]]; then
  DEVICE="a26x"
  export LOCALVERSION="$RELEASE_VERSION"
fi

# Cam Version
if [[ "$*" =~ "oldcam" ]]; then
  CONFIGVERSION="oldcam"
elif [[ "$*" =~ "newcam" ]]; then
  CONFIGVERSION="newcam"
elif [[ "$*" =~ "tencam" ]]; then
  CONFIGVERSION="tencam"
elif [[ "$*" =~ "qtihaptics" ]]; then
  CONFIGVERSION="qtihaptics"
fi

if [[ "$*" =~ "oc" ]]; then
  export LOCALVERSION="OC-$RELEASE_VERSION"
fi

# Setup Environtment
export TZ="Asia/Jakarta"
KERNEL_IMG=$KERNEL_DIR/out/arch/arm64/boot/Image.gz-dtb
SOURCE="$(git rev-parse --abbrev-ref HEAD)"
AK3_DIR=$KERNEL_DIR/anykernel/

if [[ "$*" =~ "clang" ]]; then
  # Clang Setup
  CLANG_DIR="$KERNEL_DIR/clang"
  export PATH="$KERNEL_DIR/clang/bin:$PATH"
  CCV="$("$CLANG_DIR"/bin/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')"
  LDV="$("$CLANG_DIR"/bin/ld.lld --version | head -n 1)"
  export KBUILD_COMPILER_STRING="$CCV + $LDV"
fi

export SOURCE
export ARCH=arm64
export SUBARCH=arm64
export KBUILD_BUILD_USER="XSans02"
export KBUILD_BUILD_HOST="CircleCI"

# Telegram Env
export TOKEN=$TELEGRAM_TOKEN
export BOT_MSG_URL="https://api.telegram.org/bot$TOKEN/sendMessage"
export BOT_BUILD_URL="https://api.telegram.org/bot$TOKEN/sendDocument"

sendKernel() {
	curl --progress-bar -F document=@"$1" "$BOT_BUILD_URL" \
	-F chat_id="$CHANNEL_ID"  \
	-F "disable_web_page_preview=true" \
	-F "parse_mode=html" \
	-F caption="$3 | <code>"$KERNEL_NAME"-"$DEVICE"_"$CONFIGVERSION"_"$LOCALVERSION"</code> # <code>md5: $(md5sum "$AK3_DIR"/*.zip | cut -d' ' -f1)</code> # <code>Build Took : $(("$DIFF" / 60)) Minute, $(("$DIFF" % 60)) Second</code>"
}

# Start Count
BUILD_START=$(date +"%s")

# Export Defconfig
make O=out "$DEVICE"-"$CONFIGVERSION"_defconfig

# Start Compile
if [[ "$*" =~ "clang" ]]; then
  make -j"$(nproc --all)" O=out \
          CC=clang \
          AR=llvm-ar \
          NM=llvm-nm \
          OBJCOPY=llvm-objcopy \
          OBJDUMP=llvm-objdump \
          STRIP=llvm-strip \
          CROSS_COMPILE=aarch64-linux-gnu- \
          CROSS_COMPILE_ARM32=arm-linux-gnueabi-
elif [[ "$*" =~ "gcc" ]]; then
  export CROSS_COMPILE="$KERNEL_DIR/arm64/bin/aarch64-elf-"
  export CROSS_COMPILE_ARM32="$KERNEL_DIR/arm32/bin/arm-eabi-"
  make -j"$(nproc --all)" O=out ARCH=arm64
fi

# If build error
if ! [ -a "$KERNEL_IMG" ]; then
  sendInfo "<b>Failed building kernel for <code>$DEVICE-$CONFIGVERSION</code> Please fix it...!</b>"
  exit 1
fi

# End Count and Calculate Total Build Time
BUILD_END=$(date +"%s")
DIFF=$(( BUILD_END - BUILD_START ))

# Make zip
cp -r "$KERNEL_IMG" "$AK3_DIR"/
cd "$AK3_DIR" || exit
zip -r9 "$KERNEL_NAME"-"$DEVICE"_"$CONFIGVERSION"_"$LOCALVERSION".zip ./*
cd "$KERNEL_DIR" || exit

sendKernel

rm -rf out/arch/arm64/boot/
rm -rf out/.version
rm -rf "$AK3_DIR"/*.zip
