#!/usr/bin/env bash
# Docker Kernel Build Script

SOURCE="$(git rev-parse --abbrev-ref HEAD)"
COMMIT=$(git log --pretty=format:'%s' -1)

LINUX_VERSION=$(cat < out/.config | grep Linux/arm64 | cut -d " " -f3)

if [[ "$*" =~ "clang" ]]; then
  TOOLCHAIN_DIR="clang"
  CCV="$("$TOOLCHAIN_DIR"/bin/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')"
  LDV="$("$TOOLCHAIN_DIR"/bin/ld.lld --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')"
  KBUILD_COMPILER_STRING="$CCV + $LDV"
elif [[ "$*" =~ "gcc" ]]; then
  TOOLCHAIN_DIR="arm64"
  KBUILD_COMPILER_STRING=$("$TOOLCHAIN_DIR"/bin/aarch64-elf-gcc --version | head -n 1)
fi

export SOURCE

# Telegram Env
export TOKEN=$TELEGRAM_TOKEN
export BOT_MSG_URL="https://api.telegram.org/bot$TOKEN/sendMessage"
export BOT_BUILD_URL="https://api.telegram.org/bot$TOKEN/sendDocument"

sendInfo() {
	curl -s -X POST "$BOT_MSG_URL" -d chat_id="$CHANNEL_ID" \
	-d "disable_web_page_preview=true" \
	-d "parse_mode=html" \
	-d text="$1"

}

sendInfo  "<b>==================================</b>" \
          "<b>Success Building :</b> <code>Waifu Kernel</code>" \
          "<b>Linux Version :</b> <code>$LINUX_VERSION</code>" \
          "<b>Build Date :</b> <code>$(date +"%A, %d %b %Y, %H:%M:%S")</code>" \
          "<b>Toolchain :</b> <code>$KBUILD_COMPILER_STRING</code>" \
          "<b>Last Changelog :</b> <code>$COMMIT</code>" \
          "<b>==================================</b>"
