#!/usr/bin/env bash
# Docker Kernel Build Script

# Cloning some resource
if [[ "$*" =~ "stable" ]]; then
	git clone --depth=1 https://github.com/XSans02/kernel_sdm660.git -b eas kernel
	cd kernel || exit
elif [[ "$*" =~ "beta" ]]; then
	git clone --depth=1 https://github.com/XSans02/kernel_sdm660.git -b eas-test kernel
	cd kernel || exit
fi

if [[ "$*" =~ "clang" ]]; then
  git clone --depth=1 https://github.com/kdrag0n/proton-clang.git clang
elif [[ "$*" =~ "gcc" ]]; then
  git clone --depth=1 https://github.com/chips-project/aarch64-elf.git arm64
  git clone --depth=1 https://github.com/chips-project/arm-eabi.git arm32
fi

git clone --depth=1 https://github.com/XSans02/AnyKernel3.git anykernel

# Telegram Env
export TOKEN=$TELEGRAM_TOKEN
export BOT_MSG_URL="https://api.telegram.org/bot$TOKEN/sendMessage"
export BOT_BUILD_URL="https://api.telegram.org/bot$TOKEN/sendDocument"

sendInfo() {
	curl -s -X POST "$BOT_MSG_URL" -d chat_id="$CHANNEL_ID" \
	-d "disable_web_page_preview=true" \
	-d "parse_mode=html" \
	-d text="$1"

}

sendInfo	"<b>=================================</b>" \
        	"<b>Start Building :</b> <code>Waifu Kernel</code>" \
        	"<b>Source Branch :</b> <code>$(git rev-parse --abbrev-ref HEAD)</code>" \
        	"<b>=================================</b>"
